# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "ubuntu/focal64"
    ubuntu1.vm.hostname = "ubuntu1"
    ubuntu1.vm.provision "shell", inline: <<-SHELL
      apt-get update >/dev/null 2>&1
      apt-get install -y apache2 >/dev/null 2>&1
      echo "ubuntu1" >> /var/www/html/whoami.html
      echo "WHO AM I??"
      curl -s http://localhost/whoami.html
    SHELL

  end

  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.box = "ubuntu/focal64"
    ubuntu2.vm.hostname = "ubuntu2"
    ubuntu2.vm.provision "shell", path: "configure.sh"
  end
end