# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "ubuntu/focal64"
    ubuntu1.vm.hostname = "ubuntu1"
    ubuntu1.vm.network "private_network", ip: "192.168.100.5", nic_type: "virtio", virtualbox__intnet: "keepcoding"
    ubuntu1.vm.network "forwarded_port", guest: 80, host: 8081
    ubuntu1.vm.network "forwarded_port", guest: 9090, host: 9091
    ubuntu1.vm.provider "virtualbox" do |v|
      file_to_disk = "ubuntu1_02.vmdk"
      unless File.exist?(file_to_disk)
          v.customize [ "createmedium", "disk", "--filename", file_to_disk, "--format", "vmdk", "--size", 1024 * 1 ]
      end
      v.customize [ "storageattach", :id , "--storagectl", "SCSI", "--port", "2", "--device", "0", "--type", "hdd", "--medium", file_to_disk]
    end
    ubuntu1.vm.provision "shell", inline: <<-SHELL
      apt update >/dev/null 2>&1
      apt install -y procinfo tree wget gcc make libgcc1 >/dev/null 2>&1
    SHELL
  end

  config.vm.define "centos1" do |centos1|
    centos1.vm.box = "centos/8"
    centos1.vm.hostname = "centos1"
    centos1.vm.network "private_network", nic_type: "virtio", virtualbox__intnet: "keepcoding"
    centos1.vm.network "forwarded_port", guest: 80, host: 8082
    centos1.vm.network "forwarded_port", guest: 9090, host: 9092
    centos1.vm.provider "virtualbox" do |v|
      file_to_disk = "centos1_02.vmdk"
      unless File.exist?(file_to_disk)
          v.customize [ "createmedium", "disk", "--filename", file_to_disk, "--format", "vmdk", "--size", 1024 * 1 ]
      end
      v.customize [ "storagectl", :id , "--add", "sata", "--name", "SATA1"]
      v.customize [ "storageattach", :id , "--storagectl", "SATA1", "--port", "0", "--device", "0", "--type", "hdd", "--medium", file_to_disk]
    end
    centos1.vm.provision "shell", inline: <<-SHELL
      yum install -y tree wget gcc make gcc-c++ >/dev/null 2>&1
    SHELL
  end
end
