# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "ubuntu/bionic64"
    ubuntu1.vm.hostname = "ubuntu1"
    ubuntu1.vm.network "private_network", ip: "192.168.100.5", nic_type: "virtio", virtualbox__intnet: "keepcoding"
  end

  config.vm.define "centos1" do |centos1|
    centos1.vm.box = "centos/8"
    centos1.vm.hostname = "centos1"
    centos1.vm.network "private_network", ip: "192.168.100.6", nic_type: "virtio", virtualbox__intnet: "keepcoding"
  end
end
